from typing import Any, Literal
from .waproto.whatsapp_pb2 import Message  as VerifiedNameCertificate
from .types import JID

class Message:
    conversation: str | None
    caption: str | None
    message_info: MessageInfo

    def get_extended_text_message(self) -> str | None: ...
    def get_text(self) -> str | None: ...
    def raw_proto(self) -> Any: ...

class PairingQrCode:
    code: str
    timeout: int

class MessageSource:
    sender: JID
    chat: JID

class MsgBotInfo:
    @property
    def edit_type(self) -> Literal["First", "Inner", "Last"] | None: ...
    @property
    def edit_target_id(self) -> str | None: ...
    @property
    def edit_sender_timestamp(self) -> int | None: ...
class MsgMetaInfo:
    @property
    def target_id(self) -> str | None: ...
    @property
    def target_sender(self) -> JID | None: ...
    @property
    def deprecated_lid_session(self) -> bool | None: ...
    @property
    def thread_message_id(self) -> str | None: ...
    @property
    def thread_message_sender_jid(self) -> JID | None: ...
class DeviceSentMeta:
    @property
    def destination_jid(self) -> str: ...
    @property
    def phash(self) -> str: ...

class MessageInfo:
    id: str
    type: str
    push_name: str
    @property
    def source(self) -> 'MessageSource': ...
    @property
    def multicast(self) -> bool: ...
    @property
    def server_id(self) -> str | None: ...
    @property
    def media_type(self) -> str | None: ...
    @property
    def edit(self) -> str: ...
    @property
    def bot_info(self) -> MsgBotInfo | None: ...
    @property
    def meta_info(self) -> MsgMetaInfo | None: ...
    @property
    def verified_name(self) -> VerifiedNameCertificate | None: ...
    @property
    def device_sent_meta(self) -> DeviceSentMeta | None: ...

