class FailedBuildBot(Exception): ...
class EventDispatchError(Exception): ...
class PyPayloadBuildError(Exception): ...
class UnsupportedBackend(Exception): ...
class UnsupportedEventType(Exception): ...

# Backward-compatible aliases.
class BuildBotError(FailedBuildBot): ...
class UnsupportedEventTypeError(UnsupportedEventType): ...
class UnsupportedBackendError(UnsupportedBackend): ...
