from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Final

WA_SAMPLE_RATE: Final[int]
WA_FRAME_SAMPLES: Final[int]
WA_FRAME_MS: Final[int]

def validate_audio_frame(frame: bytes | bytearray | memoryview) -> bytes: ...

@dataclass(frozen=True, slots=True)
class VideoFrame:
    data: bytes
    timestamp_us: int
    duration_us: int
    keyframe: bool
    width: int | None
    height: int | None
    orientation: int = ...

class AudioSource:
    def frames(self) -> AsyncIterator[bytes]: ...
    async def aclose(self) -> None: ...

class AudioPlayer(AudioSource):
    def __init__(self, buffer_frames: int = ...) -> None: ...
    def play(self, path: str, mode: str = ...) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def enqueue(self, path: str) -> None: ...
    def skip(self) -> None: ...
    def clear_queue(self) -> None: ...
    @property
    def state(self) -> str: ...

class VideoPlayer(VideoSource):
    def __init__(self, fps: int = ...) -> None: ...
    def play(self, path: str) -> None: ...
    def stop(self) -> None: ...

class AudioSink:
    async def write(self, frame: bytes) -> None: ...
    async def aclose(self) -> None: ...

class VideoSource:
    def frames(self) -> AsyncIterator[VideoFrame]: ...
    def rtp_timestamp_stride(self) -> int: ...
    async def aclose(self) -> None: ...

class VideoSink:
    async def write(self, frame: VideoFrame) -> None: ...
    async def aclose(self) -> None: ...

class EncodedAudioSource:
    def frames(self) -> AsyncIterator[bytes]: ...
    async def aclose(self) -> None: ...

class EncodedAudioSink:
    async def write(self, packet: bytes, timestamp: int, sequence: int) -> None: ...
    async def aclose(self) -> None: ...
