use pyo3::{Py, PyAny, Python};

use crate::events::dispatcher::Dispatcher;

pub type CallbackList = Vec<Py<PyAny>>;

pub struct EventCallbacks {
    pub connected: CallbackList,
    pub disconnected: CallbackList,
    pub logout: CallbackList,
    pub pair_success: CallbackList,
    pub pair_error: CallbackList,
    pub pairing_qr: CallbackList,
    pub pairing_code: CallbackList,
    pub qr_scanned_without_multidevice: CallbackList,
    pub client_outdated: CallbackList,
    pub message: CallbackList,
    pub receipt: CallbackList,
    pub undecryptable_message: CallbackList,
    pub notification: CallbackList,
    pub chat_presence: CallbackList,
    pub presence: CallbackList,
    pub picture_update: CallbackList,
    pub user_about_update: CallbackList,
    pub joined_group: CallbackList,
    pub group_info_update: CallbackList,
    pub contact_update: CallbackList,
    pub push_name_update: CallbackList,
    pub self_push_name_updated: CallbackList,
    pub pin_update: CallbackList,
    pub mute_update: CallbackList,
    pub archive_update: CallbackList,
    pub mark_chat_as_read_update: CallbackList,
    pub history_sync: CallbackList,
    pub offline_sync_preview: CallbackList,
    pub offline_sync_completed: CallbackList,
    pub device_list_update: CallbackList,
    pub business_status_update: CallbackList,
    pub stream_replaced: CallbackList,
    pub temporary_ban: CallbackList,
    pub connect_failure: CallbackList,
    pub stream_error: CallbackList,
    pub disappearing_mode_changed: CallbackList,
    pub contact_number_changed: CallbackList,
    pub contact_sync_requested: CallbackList,
    pub contact_updated: CallbackList,
    pub star_update: CallbackList,
}

impl EventCallbacks {
    pub fn from_dispatcher(py: Python<'_>, dispatcher: &Dispatcher) -> Self {
        Self {
            connected: dispatcher.connected_handlers(py),
            disconnected: dispatcher.disconnected_handlers(py),
            logout: dispatcher.logout_handlers(py),
            pair_success: dispatcher.pair_success_handlers(py),
            pair_error: dispatcher.pair_error_handlers(py),
            pairing_qr: dispatcher.pairing_qr_handlers(py),
            pairing_code: dispatcher.pairing_code_handlers(py),
            qr_scanned_without_multidevice: dispatcher.qr_scanned_without_multidevice_handlers(py),
            client_outdated: dispatcher.client_outdated_handlers(py),
            message: dispatcher.message_handlers(py),
            receipt: dispatcher.receipt_handlers(py),
            undecryptable_message: dispatcher.undecryptable_message_handlers(py),
            notification: dispatcher.notification_handlers(py),
            chat_presence: dispatcher.chat_presence_handlers(py),
            presence: dispatcher.presence_handlers(py),
            picture_update: dispatcher.picture_update_handlers(py),
            user_about_update: dispatcher.user_about_update_handlers(py),
            joined_group: dispatcher.joined_group_handlers(py),
            group_info_update: dispatcher.group_info_update_handlers(py),
            contact_update: dispatcher.contact_update_handlers(py),
            push_name_update: dispatcher.push_name_update_handlers(py),
            self_push_name_updated: dispatcher.self_push_name_updated_handlers(py),
            pin_update: dispatcher.pin_update_handlers(py),
            mute_update: dispatcher.mute_update_handlers(py),
            archive_update: dispatcher.archive_update_handlers(py),
            mark_chat_as_read_update: dispatcher.mark_chat_as_read_update_handlers(py),
            history_sync: dispatcher.history_sync_handlers(py),
            offline_sync_preview: dispatcher.offline_sync_preview_handlers(py),
            offline_sync_completed: dispatcher.offline_sync_completed_handlers(py),
            device_list_update: dispatcher.device_list_update_handlers(py),
            business_status_update: dispatcher.business_status_update_handlers(py),
            stream_replaced: dispatcher.stream_replaced_handlers(py),
            temporary_ban: dispatcher.temporary_ban_handlers(py),
            connect_failure: dispatcher.connect_failure_handlers(py),
            stream_error: dispatcher.stream_error_handlers(py),
            disappearing_mode_changed: dispatcher.disappearing_mode_changed_handlers(py),
            contact_number_changed: dispatcher.contact_number_changed_handlers(py),
            contact_sync_requested: dispatcher.contact_sync_requested_handlers(py),
            contact_updated: dispatcher.contact_updated_handlers(py),
            star_update: dispatcher.star_update_handlers(py),
        }
    }
}
